apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: "{{ ae_db_user }}"
    secureJsonData:
      password: "{{ ae_db_password }}"
    jsonData:
      database: "{{ ae_db_name }}"
      sslmode: disable
    isDefault: true
    editable: true
