{
 "title": "Performance",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Welcome", "type": "text", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Performance Dashboard" } },
  {
   "title": "P50 Duration (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 50 as p50" }
   ]
  },
  {
   "title": "P95 Duration (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 95 as p95" }
   ]
  },
  {
   "title": "P99 Duration (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 99 as p99" }
   ]
  }
 ]
}