---
# Fallbacks in case group_vars are not loaded
app_dir: "/opt/taskyhub"

# Naming convention fallbacks - parameterized
postgres_db_user: "th_db_{{ customer_name }}"
ae_db_user: "th_ae_{{ customer_name }}"
grafana_db_user: "th_grafana_{{ customer_name }}"

postgres_db_name: "th_db_{{ customer_name }}"
ae_db_name: "th_ae_{{ customer_name }}"
grafana_db_name: "th_grafana_{{ customer_name }}"

default_admin_username: "admin"
default_user_username: "user"

subscription_id: "11111111-1111-1111-1111-111111111111"
subscription_tier: "basic"