---
all:
  children:
    tasky_servers:
      hosts:
        tasky-manual:
          ansible_host: 127.0.0.1
          ansible_user: supertasky
          ansible_become: yes
          customer_name: local
