---
customer_name: "besty"
domain_name: "besty.taskyhub.com"

postgres_db_name: "th_db_besty"
postgres_db_user: "th_db_besty"

ae_db_name: "th_ae_besty"
ae_db_user: "th_ae_besty"

grafana_db_name: "th_grafana_besty"
grafana_db_user: "th_grafana_besty"

subscription_id: "besty-subscription-id"
subscription_tier: "pro"

default_admin_username: "admin"
default_user_username: "user"

# DO NOT put:
# app_base_path: "/opt/besty"
# compose_file: "/opt/besty/docker-compose.yml"
# app_dir: "/home/ubuntu/taskyhub"