aws_region           = "us-east-1"
instance_type        = "t3.micro"
ami_id               = "ami-024ebedf48d280810"
key_pair_name        = "ae"
ssh_private_key_path = "/path/to/your-key.pem"
customer_name        = "besty"
ui_domain            = "besty.taskyhub.xyz"
api_domain           = "besty.taskyhub.xyz"
